import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ConvexClientProvider } from '@/providers/convex-client-providers';
import { Toaster } from '@/components/ui/sonner';

import { ModalProvider } from '@/providers/modal-provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html suppressHydrationWarning={true} lang='en'>
			<body suppressHydrationWarning={true} className={inter.className}>
				<ConvexClientProvider>
					<Toaster />
					<ModalProvider />
					{children}
				</ConvexClientProvider>
			</body>
		</html>
	);
}
